export const occupations = [
  "Software Engineer",
  "Data Scientist",
  "Product Manager",
  "Sales Executive",
  "Marketing Manager",
  "UX/UI Designer",
  "Financial Analyst",
  "Project Manager",
  "Business Analyst",
  "Human Resources Manager",
  "Operations Manager",
  "Customer Success Manager",
  "Full Stack Developer",
  "Content Manager",
  "Creative Director",
  "IT Support Specialist",
  "DevOps Engineer",
  "Network Administrator",
  "Frontend Developer",
  "Backend Developer",
  "Cloud Architect",
  "Security Analyst",
  "Software Architect",
  "Business Development Manager",
  "Recruiter",
  "Graphic Designer",
  "Public Relations Specialist",
  "Chief Marketing Officer",
  "Chief Executive Officer",
  "Chief Technology Officer",
  "Chief Financial Officer",
  "Data Engineer",
  "Digital Marketing Specialist",
  "Legal Counsel",
  "Office Manager",
  "Accountant",
  "Account Manager",
  "Sales Manager",
  "Customer Service Representative",
  "Quality Assurance Engineer",
  "Electrical Engineer",
  "Mechanical Engineer",
  "Civil Engineer",
  "Construction Manager",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Medical Doctor",
  "Nurse",
  "Pharmacist",
  "Occupational Therapist",
  "Dentist",
  "Chiropractor",
  "Veterinarian",
  "Clinical Research Associate",
  "Laboratory Technician",
  "Environmental Scientist",
  "Compliance Officer",
  "Legal Assistant",
  "Paralegal",
  "Event Manager",
  "Real Estate Agent",
  "Property Manager",
  "Retail Manager",
  "Store Manager",
  "Hospitality Manager",
  "Hotel Manager",
  "Restaurant Manager",
  "Chef",
  "Bartender",
  "Travel Agent",
  "Flight Attendant",
  "Airline Pilot",
  "Automotive Engineer",
  "Civil Service Administrator",
  "Customs Officer",
  "Firefighter",
  "Police Officer",
  "Security Guard",
  "Translator",
  "Interpreter",
  "Writer",
  "Journalist",
  "Doctor",
  "Student",
  "Editor",
  "Copywriter",
  "Fitness Instructor",
  "Personal Trainer",
  "Nutritionist",
  "Psychologist",
  "Therapist",
  "Social Worker",
  "Research Scientist",
  "Statistician",
  "Professor",
  "Lecturer",
  "School Teacher",
  "Substitute Teacher",
  "Teaching Assistant",
  "Librarian",
  "Janitor",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Mechanic",
  "Construction Worker",
  "Roofer",
  "Welder",
  "Painter",
  "Taxi Driver",
  "Bus Driver",
  "Truck Driver",
  "Courier",
  "Delivery Driver",
  "Warehouse Worker",
  "Forklift Operator",
  "Factory Worker",
  "Manufacturing Engineer",
  "Quality Control Inspector",
  "Purchasing Manager",
  "Food Scientist",
  "Biochemist",
  "Phlebotomist",
  "Radiologic Technologist",
  "Surgeon",
  "Anesthesiologist",
  "Pediatrician",
  "Oncologist",
  "Dermatologist",
  "Psychiatrist",
  "Veterinary Technician",
  "Technical Support Specialist",
  "Software Tester",
  "Solutions Architect",
  "Mobile Application Developer",
  "Blockchain Developer",
  "AI Engineer",
  "Machine Learning Engineer",
  "Data Analyst",
  "Database Administrator",
  "Information Security Analyst",
  "SEO Specialist",
  "Social Media Specialist",
  "Youtuber",
  "Brand Manager",
  "Account Executive",
  "E-commerce Manager",
  "Retail Associate",
  "Customer Experience Manager",
  "Food and Beverage Manager",
  "Facilities Manager",
  "Event Coordinator",
  "Communications Manager",
  "Corporate Trainer",
  "Learning and Development Manager",
  "Technical Recruiter",
  "Product Designer",
  "Instructional Designer",
  "Video Editor",
  "Sound Engineer",
  "3D Animator",
  "Game Developer",
  "Voice Actor",
  "Model",
  "Makeup Artist",
  "Costume Designer",
  "Fashion Designer",
  "Merchandiser",
  "Journalism Writer",
  "Architect",
  "Urban Planner",
  "Land Surveyor",
  "Geologist",
  "Biotechnologist",
  "Marine Biologist",
  "Forestry Technician",
  "Agricultural Scientist",
  "Food Safety Inspector",
  "Patent Examiner",
  "Patent Lawyer",
  "Corporate Lawyer",
  "Footballer",
  "Actor",
  "Actress",
  "Public Defender",
  "District Attorney",
  "Judge",
  "Court Clerk",
  "Customs Inspector",
  "Border Patrol Agent",
  "Prison Guard",
  "Correctional Officer",
  "Mern Stack Developer",
  "Real Estate Broker",
  "Construction Foreman",
  "Building Inspector",
  "Maintenance Worker",
  "HVAC Technician",
  "Water Treatment Operator",
  "Solar Energy Technician",
  "Wind Turbine Technician",
  "Nuclear Engineer",
  "Aerospace Engineer",
  "Automotive Technician",
  "Robotics Engineer",
  "Biomedical Engineer",
  "Chemical Engineer",
  "Petroleum Engineer",
  "Geophysicist",
  "Cartographer",
  "Archivist",
  "Curator",
  "Art Director",
  "Exhibit Designer",
  "Museum Curator",
  "Museum Technician",
  "Musician",
  "Composer",
  "Conductor",
  "Producer",
  "Director",
  "Screenwriter",
  "Cinematographer",
  "Film Editor",
  "Production Assistant",
  "Lighting Technician",
  "Sound Mixer",
  "Radio Host",
  "Podcast Host",
  "Videographer",
  "Photographer",
  "Drone Operator",
  "Digital Artist",
  "Voiceover Artist",
  "IDK",
  "Engineer",
].sort();

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Swaziland",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Mars",
  "Moon",
].sort();
